title: Set the pins for a single LED
hero_image: images/banner.png
description: sing-led-pins description
version: 4
listed: false
copyedit: false
last_tested: "2022-02-08"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
