title: Définir les broches pour une seule LED
hero_image: images/banner.png
description: Définit les broches pour une seule LED sur un Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-08"
steps:
  - 
    title: Définir les broches pour une seule LED
